name: Go Release

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
        with:
          node-version: "16.x"
          cache: "yarn"
          cache-dependency-path: "assets/yarn.lock"
      
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y upgrade
          sudo apt-get -y install build-essential zip
          sudo apt-get -y install gcc-mingw-w64-x86-64
          sudo apt-get -y install gcc-arm-linux-gnueabihf libc6-dev-armhf-cross
          sudo apt-get -y install gcc-aarch64-linux-gnu libc6-dev-arm64-cross
      
      - name: Build
        run: |
          rm -f assets.zip
          chmod +x build.sh
          ./build.sh -a

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: linux_amd64_random-donate
          path: build/linux_amd64_random_donate

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: linux_arm64_random_donate
          path: build/linux_arm64_random_donate

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: darwin_amd64_random_donate
          path: build/darwin_amd64_random_donate

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: windows_amd64_random_donate.exe
          path: build/windows_amd64_random_donate.exe
